name: V2Ray Proxy Tester

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

env:
  SUBSCRIPTION_URL: "https:/raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2"
  SPEED_TEST_URL: "http://www.gstatic.com/generate_204"
  TIMEOUT: 10
  BLACKLIST_KEYWORDS: "CN,中国,移动,联通,电信"

jobs:
  test-proxies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl wget unzip
        sudo bash -c "$(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)" -- -f
        /usr/local/bin/v2ray version
        
    - name: Run proxy tester
      run: |
        mkdir -p config output
        
        # 下载并完整显示订阅内容(保存到文件)
        curl -s "$SUBSCRIPTION_URL" > subscription.txt
        echo "完整订阅内容已保存到 subscription.txt"
        echo "文件大小: $(wc -c < subscription.txt) 字节"
        
        # 改进的解码方式
        DECODED=$(base64 -d subscription.txt 2>/dev/null || cat subscription.txt)
        echo "解码后的订阅内容:"
        echo "$DECODED"
        echo "$DECODED" > decoded.txt
        
        # 改进的链接提取
        VMESS_LIST=$(grep -o 'vmess://[^ ]*' decoded.txt || true)
        SS_LIST=$(grep -o 'ss://[^ ]*' decoded.txt || true)
        
        echo "找到 vmess 链接: $(echo "$VMESS_LIST" | wc -w) 个"
        echo "找到 ss 链接: $(echo "$SS_LIST" | wc -w) 个"
        
        # 合并所有代理链接
        ALL_LINKS=$(echo -e "$VMESS_LIST\n$SS_LIST")
        echo "总共找到代理链接: $(echo "$ALL_LINKS" | wc -l) 个"
        
        # 测试逻辑(同前)
        VALID_PROXIES=()
        INDEX=0
        
        for LINK in $ALL_LINKS; do
          ((INDEX++))
          echo -e "\n测试代理 $INDEX: ${LINK:0:100}..."
          
          # 过滤和测试逻辑保持不变...
          # [...原有测试代码...]
        done
        
        # 保存结果
        if [ ${#VALID_PROXIES[@]} -gt 0 ]; then
          printf '%s\n' "${VALID_PROXIES[@]}" > output/valid_proxies.txt
          echo "有效代理示例:"
          head -n 3 output/valid_proxies.txt
        else
          echo "empty" > output/valid_proxies.txt
        fi
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: proxy-results
        path: |
          output/valid_proxies.txt
          decoded.txt
          subscription.txt