name: Proxy Checker

on:
  schedule:
    - cron: '0 0 * * *'  # 每日UTC时间0点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 超时时间
    
    steps:
    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y shadowsocks-libev curl wget unzip
        wget https://github.com/XTLS/Xray-core/releases/download/v1.8.11/Xray-linux-64.zip
        unzip Xray-linux-64.zip
        sudo mv xray /usr/local/bin/
        sudo chmod +x /usr/local/bin/xray
        xray --version
        rm Xray-linux-64.zip geoip.dat geosite.dat README.md LICENSE
        
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        
    - name: 运行检测脚本
      run: |
        python3 proxy_checker.py proxies/extracted_proxies.txt proxies/available_proxies.txt
      env:
        PYTHONWARNINGS: "default"
        
    - name: 提交变更
      run: |
        git config --global user.name "DSLZL"
        git config --global user.email "q2891362919@163.com"
        git add available_proxies.txt
        git commit -m "自动更新可用代理列表 [$(date +'%Y-%m-%d %H:%M')]"
        git push